-- Flyway Migration V1: Initial schema for order-cancellation-demo
-- ================================================================

CREATE TABLE IF NOT EXISTS orders (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status      VARCHAR(20)  NOT NULL DEFAULT 'UNPAID',
    approach    VARCHAR(30)  NOT NULL,
    amount      NUMERIC(19,4) NOT NULL,
    created_at  TIMESTAMP    NOT NULL,
    expire_at   TIMESTAMP    NOT NULL,
    version     BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT chk_status CHECK (status IN ('UNPAID', 'PAID', 'CANCELLED')),
    CONSTRAINT chk_amount CHECK (amount > 0)
);

-- Index for DB polling scheduler: quickly find expired UNPAID orders
CREATE INDEX IF NOT EXISTS idx_orders_status_expire_approach
    ON orders (status, expire_at, approach);

-- ShedLock table for distributed scheduler coordination
CREATE TABLE IF NOT EXISTS shedlock (
    name       VARCHAR(64)  NOT NULL,
    lock_until TIMESTAMP    NOT NULL,
    locked_at  TIMESTAMP    NOT NULL,
    locked_by  VARCHAR(255) NOT NULL,
    PRIMARY KEY (name)
);
